zurg: v1
token: debrid_token
check_for_changes_every_secs: 10
enable_repair: true
auto_delete_rar_torrents: true
on_library_update: sh plex_update.sh "$@"
directories:
  shows:
    group_order: 20
    group: media
    filters:
      - has_episodes: true

  movies:
    group_order: 30
    group: media
    only_show_the_biggest_file: true
    filters:
      - regex: /.*/
